---
output: github_document
always_allow_html: true
---

# `targets` workflow for iSSA with `amt`

```{r, results = 'hide', echo = FALSE}
targets::tar_visnetwork(TRUE)
```


## R setup

```{r, eval = FALSE}
options(repos = c(
    ropensci = 'https://ropensci.r-universe.dev',
    tidyverse = 'https://tidyverse.r-universe.dev',
    rspatial = 'https://rspatial.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

install.packages(c('data.table', 'amt', 'sf', 'ggplot2', 'raster', 'qs', 'terra' ))
```

## Data setup

Run through `scripts/prep-fisher.R`.


## Run the workflow

```{r}
library(targets)
tar_make()
```


## Explore results

See `scripts/explore-results.R` for a full example. 

Below is an example of how to interact with `targets` outputs - but don't run them in this README. Copy over to a separate R script or check out the explore results script. 

```{r, eval = FALSE}
library(targets)

## Run the full workflow
tar_make()

## Inspect output with tar_read or tar_load
# *Read* one branch (individual in this case)
tar_read(tracks, 1)
tar_read(tracks, 2)

# Or all combined
tar_read(tracks)

# Plot all distributions
tar_read(distributions)

# *Load* all random steps and extracted landscape variables
tar_load(mergelc)
```
